package com.rhodso.app;

public class bingoLines {
    static String bingoLines[] = {
        "Richie says \"Your man\"",
        "Scottish accent",
        "Richie goes blasting",
        "Combat encounter",
        "Late start",
        "Discord connection issues",
        "Riche offers to fix something for someone",
        "Nat 1",
        "Nat 20",
        "Vapey Jack voice",
        "The group abandons a perfectly good quest",
        "Richie defiles a corple",
        "Someone makes a joke about Richie defiling a coprse",
        "New zealand accent",
        "Azzeth voice",
        "The group does something despicable",
        "Intimidation attempt",
        "The druids transform into something",
        "Persuiasion attempt",
        "Richie takes a shot out of game",
        "Innuendo",
        "Richie doesn't order alcohol in game",
        "Richie uses guidance",
        "Richie uses mending",
        "Richie uses mage hand",
        "Richie uses mage hand to find traps",
        "Tangent",
        "Jonah has fabric in camera background",
        "Rachael worries about Vapey Jack",
        "Vapey Jack gets a belly rub",
        "Sound issues",
        "Someone takes it out of control",
        "Someone says \"seemingly\" 5 times",
        "Theft",
        "\"Accidental\" harm",
        "Haggling",
        "Someone makes a joke about Jonah's sexuality",
        "Someone makes a decision that bewilders the group",
        "The group potentially destroys a location",
        "Someone is clumsy",
        "Heist planning",
        "Riche uses a spell to be lazy",
        "Someone mistypes a discord roll",
        "Richie writes some software to do something dnd related",
        "Random threat out of nowhere",
        "Richie opens a bag of midget gems"
    };

    static String[] getLines(){ return bingoLines; }    
}
